service: expressInAWSDemoApp #Name of your App

provider:
  name: aws
  runtime: nodejs14.x # Node JS version
  memorySize: 512
  timeout: 15
  stage: development
  region: us-east-2 # AWS region

functions:
  api:
    handler: lambda.handler
    events:
      - http: ANY {proxy+}
      - http: ANY /
